language: go

install:
    - cd "${HOME}"
    - wget -O libgit2-0.22.1.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.1.tar.gz
    - tar -xzvf libgit2-0.22.1.tar.gz
    - cd libgit2-0.22.1 && mkdir build && cd build
    - cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX=/usr/local .. && make && sudo make install
    - sudo ldconfig
    - cd "${TRAVIS_BUILD_DIR}"

addons:
  artifacts:
    key: AKIAJ4FZVZXTBDSZF2RA
    secret:
      secure: EcZAnKJR5m1SkvMPfBKck/sNVyB8nP1+PhV14t7bi9veaGvfxKYk5oHZkkFvuFAaWIShbS4lMct3ZRa7fLnqYpDAIWIJ2mUa4TUJPmgmhODBrjnVbeu21/VELhrdTEPzAYtNuAOtZjIVjc65x1OUM8YAy2NpJHNdBQU368n6TqQ=
    bucket: stashify-artifacts
    paths: [ "$HOME/gopath/bin/stashify" ]
    debug: true
